# Generated by Django 4.2.3 on 2023-08-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_category_alter_medicalequipment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalequipment',
            name='category',
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='image',
            field=models.ImageField(default='download.jfif', upload_to='equipment_images/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
